name: Feature branch build

on:
  push:
    branches:
      - '**'

env:
  DEFAULT_BRANCH: main
  AWS_ACCOUNT: ${{ vars.AWS_ACCOUNT }}
  AWS_DEPLOYMENT_REGION: ${{ vars.AWS_DEPLOYMENT_REGION }}
  HOSTED_ZONE_ID: ${{ vars.HOSTED_ZONE_ID }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Prepare variables
        run: echo SAFE_SOURCE_NAME=$(echo "${{ github.ref_name }}" | sed -r 's/[/.@_]+/-/g') >> $GITHUB_ENV

      - name: Install, type-check, lint
        run: |
          npm ci
          npm run type-check

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ vars.AWS_AUTH_ROLE }}

      - name: Deploy infrastructure
        if: env.SAFE_SOURCE_NAME == env.DEFAULT_BRANCH
        run: npm run deploy

      - name: Diff infrastructure
        if: env.SAFE_SOURCE_NAME != env.DEFAULT_BRANCH
        run: npm run cdk-diff-stacks
